apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: nile
  labels:
    tags.datadoghq.com/service: auth-server
    tags.datadoghq.com/env: {{ .Values.datadog.env }}
    tags.datadoghq.com/version: "{{ default .Chart.AppVersion .Values.image.tag }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-server
        tags.datadoghq.com/service: auth-server
        tags.datadoghq.com/env: {{ .Values.datadog.env }}
        tags.datadoghq.com/version: "{{ default .Chart.AppVersion .Values.image.tag }}"
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/auth-server.logs: '[{}]'
    spec:
      containers:
      - name: auth-server
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
          - name: DISABLE_LOGGING
            value: "true"
          - name: JWT_SECRET_KEY
            value: "{{ .Values.jwtSecretKey }}"
          - name: KHNUM
            value: "{{ .Values.khnumHostname }}"
          - name: NEXTAUTH_SECRET
            value: "{{ .Values.nextauthSecret }}"
          - name: CONSOLE_SESSION
            value: "{{ .Values.consoleSession }}"
          - name: SENTRY_AUTH_TOKEN
            value: "{{ .Values.sentry.authToken }}"
          - name: SENTRY_DSN
            value: "{{ .Values.sentry.dsn }}"
          - name: KHNUM_USER
            value: "{{ .Values.khnumUser }}"
          - name: KHNUM_PASSWORD
            value: "{{ .Values.khnumPassword }}"
        ports:
          - containerPort: 3001
            name: http
            protocol: TCP
        readinessProbe:
          httpGet:
            port: http
            path: "/ready"
