apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nile-auth
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  defaultBackend:
    service:
      name: khnum
      port:
        number: 8080
  rules:
{{- if .Values.ingress.globalControlPlaneHost }}
    - host: "{{ .Values.ingress.globalControlPlaneHost }}"
      http:
        paths:
          - backend:
              service:
                name: khnum
                port:
                  number: 8080
            path: /
            pathType: Prefix
{{- end }}
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /v2/
            pathType: Prefix
            backend:
              service:
                name: nile-auth
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: khnum
                port:
                  number: 8080
    - host: '*.{{ .Values.ingress.host }}'
      http:
        paths:
          - path: /v2/
            pathType: Prefix
            backend:
              service:
                name: nile-auth
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: khnum
                port:
                  number: 8080
