name: Auto-Tag

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tag:
    name: Bump version and push tag
    runs-on: public-ubuntu-x64-2-core
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: niledatabase/bump-git-tag-action@v0.0.17
        id: tag
        with:
          main-branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_USER_TOKEN }}
