name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

on:
  push:
    branches:
      - '**'

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}
  ECR_IMAGE: 483388953608.dkr.ecr.us-west-2.amazonaws.com/nile-auth
  AWS_REGION: us-west-2

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          WITH_V: true
          PRERELEASE: true

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha,format=short
            type=sha,format=long
            type=raw,value=${{ steps.tag.outputs.tag }}
            type=raw,value=ts-{{date 'X'}}-sha-{{sha}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          images: |
            ${{ env.GHCR_IMAGE }}
            ${{ env.ECR_IMAGE }}

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::483388953608:role/github-role-Role-MIMIOJ3EPX6V
          role-session-name: khnum-github-action

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 483388953608.dkr.ecr.us-west-2.amazonaws.com

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          file: apps/server/Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
