name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

on:
  push:
    branches-ignore:
      - 'main'
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install deps
        run: yarn install --immutable

      - name: test
        run: yarn test
  docker:
    uses: niledatabase/workflows/.github/workflows/docker-multi-arch.yaml@main
    needs: [ "test" ]
    permissions:
      contents: read
      packages: write
      id-token: write

  helm:
    uses: niledatabase/workflows/.github/workflows/helm.yaml@main
    needs: [ "docker" ]
    permissions:
      contents: read
      packages: write
    with:
      path: charts/server
