name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

on:
  push:
    branches:
      - "**"

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}
  ECR_IMAGE: 483388953608.dkr.ecr.us-west-2.amazonaws.com/nile-auth
  AWS_REGION: us-west-2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install deps
        run: yarn install --immutable

      - name: test
        run: yarn test
  docker:
    needs: test
    runs-on: ubuntu-latest-4core
    outputs:
      tag: ${{ steps.tag.outputs.new_version }}
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha,format=short
            type=sha,format=long
            type=raw,value=${{ steps.tag.outputs.new_version }}
            type=raw,value=ts-{{date 'X'}}-sha-{{sha}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          images: |
            ${{ env.GHCR_IMAGE }}
            ${{ env.ECR_IMAGE }}

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::483388953608:role/github-role-Role-MIMIOJ3EPX6V
          role-session-name: khnum-github-action

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 483388953608.dkr.ecr.us-west-2.amazonaws.com

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          file: apps/server/Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.new_version }}

  helm:
    runs-on: ubuntu-latest
    needs: docker
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4
        with:
          version: "3.16.2"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::483388953608:role/github-role-Role-MIMIOJ3EPX6V
          role-session-name: khnum-github-action

      - name: Helm login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
          aws ecr get-login-password \
            --region ${{ env.AWS_REGION }} | helm registry login \
            --username AWS \
            --password-stdin 483388953608.dkr.ecr.us-west-2.amazonaws.com

      - name: Package helm chart
        run: |
          helm package --app-version '${{ needs.docker.outputs.tag }}' --version '${{ needs.docker.outputs.tag }}' ./charts/server

      - name: Push helm chart
        run: |
          helm push nile-auth-${{ needs.docker.outputs.tag }}.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
          helm push nile-auth-${{ needs.docker.outputs.tag }}.tgz oci://483388953608.dkr.ecr.us-west-2.amazonaws.com/helm-charts
