name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

on:
  push:

jobs:
  test:
    runs-on: public-ubuntu-x64-2-core
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install deps
        run: yarn install --immutable

      - name: test
        run: yarn test
  tag:
    runs-on: public-ubuntu-x64-2-core
    needs: [ "test" ]
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Bump tag
        id: tag
        uses: niledatabase/bump-git-tag-action@v0.0.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    uses: niledatabase/workflows/.github/workflows/docker-multi-arch-v2.yaml@main
    needs: [ "tag" ]
    permissions:
      contents: read
      packages: write
    with:
      file: 'apps/server/Dockerfile'
      tags: |
        type=raw,value=${{ needs.tag.outputs.tag }}
        type=sha
        type=sha,format=long

  publish-helm-chart:
    name: Publish Helm Chart
    runs-on: public-ubuntu-x64-2-core
    needs: [ "docker", "tag" ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Push helm chart
        uses: niledatabase/workflows/.github/actions/helm-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.tag.outputs.tag }}
          path: ./charts/server
          app_version: sha-${{ github.sha }}
